kilo: main.cpp
	$(CC) main.cpp -o kilo.exe -Wall -Wextra -pedantic







#all:
#	g++ main.cpp -o kilo.exe -Iinclude -Llib -mwindows -Wfatal-errors

#run:
#	-taskkill /F /IM kilo.exe /T 2>nul
#	@$(MAKE) -s all
#	@cmd /c start kilo.exe